require: rubocop-rails

Rails:
  Enabled: true
Metrics/LineLength:
  Max: 160
Metrics/MethodLength:
  Max: 40
Metrics/BlockLength:
  Max: 45
Style/Documentation:
  Enabled: false
Metrics/AbcSize:
  Max: 30
